# Generated by Django 2.0.5 on 2018-05-27 03:06

from django.db import migrations


def insert_aws_regions(apps, schema_editor):
    AWSRegion = apps.get_model('provision_aws', 'AWSRegion')
    aws_regions = [
        AWSRegion(
            name='ap-northeast-1',
        ),
        AWSRegion(
            name='ap-northeast-2',
        ),
        AWSRegion(
            name='ap-northeast-3',
        ),
        AWSRegion(
            name='ap-south-1',
        ),
        AWSRegion(
            name='ap-southeast-1',
        ),
        AWSRegion(
            name='ap-southeast-2',
        ),
        AWSRegion(
            name='ca-central-1',
        ),
        AWSRegion(
            name='cn-north-1',
        ),
        AWSRegion(
            name='eu-central-1',
        ),
        AWSRegion(
            name='eu-west-1',
        ),
        AWSRegion(
            name='eu-west-2',
        ),
        AWSRegion(
            name='eu-west-3',
        ),
        AWSRegion(
            name='sa-east-1',
        ),
        AWSRegion(
            name='us-east-1',
        ),
        AWSRegion(
            name='us-east-2',
        ),
        AWSRegion(
            name='us-west-1',
        ),
        AWSRegion(
            name='us-west-2',
        ),
    ]
    for aws_region in aws_regions:
        aws_region.save()


class Migration(migrations.Migration):

    dependencies = [
        ('provision_aws', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_aws_regions)
    ]
