# Generated by Django 2.0.5 on 2018-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provision_aws', '0002_insert_aws_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscluster',
            name='playbook_pid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Playbook PID'),
        ),
    ]
