---

# https://access.redhat.com/documentation/en-us/reference_architectures/2018/html/deploying_and_managing_openshift_3.9_on_azure/red_hat_openshift_container_platform_instance_prerequisites#creating_a_resource_group

# 2.2. Creating a Resource Group

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group_name }}"
    location: "{{ azure_region }}"

# 2.3. Creating a Red Hat Enterprise Linux Base Image
# TODO: Generate RHEL image from KVM image

# 2.4. Creation of Red Hat OpenShift Container Platform Networks

- name: Create virtual network
  azure_rm_virtualnetwork:
    name: "{{ azure_virtual_network_name }}"
    resource_group: "{{ azure_resource_group_name }}"
    address_prefixes_cidr:
      - 10.0.0.0/16

- name: Create subnet
  azure_rm_subnet:
    name: "{{ azure_subnet_name }}"
    resource_group: "{{ azure_resource_group_name }}"
    virtual_network_name: "{{ azure_virtual_network_name }}"
    address_prefix_cidr: 10.0.0.0/24

# 2.5. Creating Network Security Groups

- name: Create bastion security group
  azure_rm_securitygroup:
    name: "{{ azure_security_group_bastion }}"
    resource_group: "{{ azure_resource_group_name }}"
    rules:
      - name: "{{ azure_security_group_bastion }}-ssh"
        destination_port_range: 22
        access: Allow
        protocol: Tcp
        priority: 500
      - name: "{{ azure_security_group_bastion }}-internal"
        source_address_prefix: VirtualNetwork
        access: Allow
        protocol: "*"
        priority: 600

- name: Create master security group
  azure_rm_securitygroup:
    name: "{{ azure_security_group_master }}"
    resource_group: "{{ azure_resource_group_name }}"
    rules:
      - name: "{{ azure_security_group_master }}-api"
        destination_port_range: 443
        access: Allow
        protocol: Tcp
        priority: 500
      - name: "{{ azure_security_group_master }}-internal"
        source_address_prefix: VirtualNetwork
        access: Allow
        protocol: "*"
        priority: 600

- name: Create infra security group
  azure_rm_securitygroup:
    name: "{{ azure_security_group_infra }}"
    resource_group: "{{ azure_resource_group_name }}"
    rules:
      - name: "{{ azure_security_group_infra }}-router"
        destination_port_range:
          - 80
          - 443
        access: Allow
        protocol: Tcp
        priority: 500
      - name: "{{ azure_security_group_infra }}-internal"
        source_address_prefix: VirtualNetwork
        access: Allow
        protocol: "*"
        priority: 600

# 2.7. Creating Instances for Red Hat OpenShift Container Platform

- name: Create bastion network interface
  azure_rm_networkinterface:
    name: "{{ azure_network_interface_bastion }}"
    resource_group: "{{ azure_resource_group_name }}"
    virtual_network_name: "{{ azure_virtual_network_name }}"
    subnet_name: "{{ azure_subnet_name }}"
    security_group_name: "{{ azure_security_group_bastion }}"
    ip_configurations:
      name: ip-config
      public_ip_address_name: public-ip
      public_ip_allocation_method: Static
      primary: yes

  with_items:
    - "{{ azure_network_interface_bastion }}"
    - "{{ azure_network_interface_master }}"
    - "{{ azure_network_interface_infra }}"
